apiVersion: v1
kind: ServiceAccount
metadata:
  name: kfn-operator
  namespace: kfn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kfn-operator-role
rules:
- apiGroups: ["kfn.dajac.io"]
  resources: ["functions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kfn.dajac.io"]
  resources: ["functions/status"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kfn-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kfn-operator-role
subjects:
- kind: ServiceAccount
  name: kfn-operator
  namespace: kfn
